;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;
;;;;

(define baker-conf '(1 2 3 4))
(define cooper-conf '(2 3 4 5))
(define fletcher-conf '(2 3 4))
(define miller-conf '(3 4 5))
(define smith-conf '(1 2 3 4 5))

(define (multiple-dwelling init-confs)
  (define (try baker cooper fletcher miller smith confs)
    (cond ((null? confs)
           (if (null? baker)
               'NO-ANSWER
               (try (cdr baker) cooper fletcher miller smith (cons (car baker) confs))))
          ((= (length confs) 1)
           (if (null? cooper)
               (try baker cooper-conf fletcher-conf miller-conf smith-conf (cdr confs))
               (if (memq (car cooper) confs)
                   (try baker (cdr cooper) fletcher miller smith confs)
                   (try baker (cdr cooper) fletcher miller smith (cons (car cooper) confs)))))
          ((= (length confs) 2)
           (if (null? fletcher)
               (try baker cooper fletcher-conf miller-conf smith-conf (cdr confs))
               (if (and (not (memq (car fletcher) confs))
                        (not (= (abs (- (car fletcher) (car confs))) 1)))
                   (try baker cooper (cdr fletcher) miller smith (cons (car fletcher) confs))
                   (try baker cooper (cdr fletcher) miller smith confs))))
          ((= (length confs) 3)
           (if (null? miller)
               (try baker cooper fletcher miller-conf smith-conf (cdr confs))
               (if (and (not (memq (car miller) confs))
                        (> (car miller) (cadr confs)))
                   (try baker cooper fletcher (cdr miller) smith (cons (car miller) confs))
                   (try baker cooper fletcher (cdr miller) smith confs))))
          ((= (length confs) 4)
           (if (null? smith)
               (try baker cooper fletcher miller smith-conf (cdr confs))
               (if (and (not (memq (car smith) confs))
                        (not (= (abs (- (car smith) (cadr confs))) 1)))
                   (try baker cooper fletcher miller (cdr smith) (cons (car smith) confs))
                   (try baker cooper fletcher miller (cdr smith) confs))))
          ((= (length confs) 5)
           confs)))
  (try baker-conf cooper-conf fletcher-conf miller-conf smith-conf init-confs))
